trigger:
  - main

schedules:
- cron: "0 */12 * * * "
  displayName: Build every 12 hours
  branches:
    include:
    - main
  always: true

resources:
  repositories:
    - repository: templates
      type: git
      ref: refs/heads/master
      name: pipeline-templates

extends:
  template: templates\js\template.yml@templates
  parameters:
    deploy_application: true
