 
version: "3.8"

volumes:
    sql-server:

services:     
    react-advanced:
        image: react-advanced
        container_name: react-advanced
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
          - "3000:3000"