FROM node:12-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --silent

COPY . ./
CMD ["npm", "run", "dev"]

RUN apk --no-cache add curl
HEALTHCHECK CMD curl -f http://localhost:3000/health

EXPOSE 3000
