services:     
    react-nextjs-sample:
        image: react-nextjs-sample
        container_name: react-nextjs-sample
        build:
            context: ./
            dockerfile: Dockerfile.Dev
        volumes:
            - ./:/app
            - /app/node_modules
            - /app/.next
        ports:
          - "3000:3000"