services:
    react-nextjs-boilerplate:
        image: react-nextjs-boilerplate
        container_name: react-nextjs-boilerplate
        build:
            context: ./
            dockerfile: Dockerfile.Dev
        volumes:
            - ./:/app
            - /app/node_modules
            - /app/.next
        ports:
          - "3000:3000"
