kind: Service
apiVersion: v1
metadata:
  name: react-nextjs-boilerplate-service
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: react-nextjs-boilerplate
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
  
